---
name: Test and Build

permissions: read-all

on:
  pull_request:
  #   branches: [ $default-branch ]
  # push:
  #   branches: [ $default-branch ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]  # MacOS is broken, for now
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display disk space (before)
        run: df -h

      - name: Node cleanup
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Display disk space (after)
        run: df -h

      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
