---
name: Test

permissions: read-all

on:
  pull_request:

  push: # May be needed to fill GHA cache in a way that PRs can use it
    branches: [ main ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]  # MacOS is broken, for now
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      # Needed for cache action to work
      actions: write
    steps:
      - name: Display disk space (before)
        run: df -h

      - name: Node cleanup
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune --all --force

      - name: Display disk space (after)
        run: df -h

      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@b426b118b6dc86d6952988d396aa7c6b09776d08  # TODO: Switch to a numbered version after next release
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/devenv.lock') }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 5G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or, last accessed more than this number of seconds ago
          # relative to the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: 0
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never
          # include cargo paths in the cache
          paths: |
            ~/.cargo/bin
            ~/.cargo/git/db
            ~/.cargo/registry
            target/

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: devenv test
        run: |
          devenv test

      - name: devenv build
        run: devenv build

      # TODO: Maybe try running commands in container:local directly, rather than indirectly?
      - name: Build local container, verify container loads into docker
        run: |
          devenv build outputs.oic-fox-fuckery-prod-local --verbose
          # devenv tasks run container:local
          # docker image inspect doot/oic-fox-fuckery:latest | jq -e 'any(.[].RepoTags[]; . == "doot/oic-fox-fuckery:latest")' > /dev/null
